-repackageclasses
-allowaccessmodification
-optimizationpasses 10
-keepattributes SourceFile, LineNumberTable
-keep class com.pechuro.bsuirschedule.remote.api.** { *; }
-keep class kotlin.coroutines.Continuation